apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kubernetes-platform
  title: Multi-Cloud Kubernetes Platform
  description: Production-ready Kubernetes platform with GitOps, observability, and security on AWS EKS, Azure AKS, or GCP GKE
  tags:
    - kubernetes
    - multi-cloud
    - gitops
    - platform
    - terraform
    - recommended
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Project Configuration
      required:
        - projectName
        - environment
        - cloudProvider
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name for the Kubernetes platform (lowercase, hyphens allowed)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          enum:
            - dev
            - staging
            - production
          default: dev
        cloudProvider:
          title: Cloud Provider
          type: string
          enum:
            - aws
            - azure
            - gcp
          enumNames:
            - Amazon Web Services (EKS)
            - Microsoft Azure (AKS)
            - Google Cloud Platform (GKE)
          default: aws

    - title: AWS Configuration
      dependencies:
        cloudProvider:
          oneOf:
            - properties:
                cloudProvider:
                  const: aws
                awsRegion:
                  title: AWS Region
                  type: string
                  enum:
                    - us-east-1
                    - us-west-2
                    - eu-west-1
                    - eu-central-1
                    - ap-southeast-1
                  default: us-east-1

    - title: Azure Configuration
      dependencies:
        cloudProvider:
          oneOf:
            - properties:
                cloudProvider:
                  const: azure
                azureRegion:
                  title: Azure Region
                  type: string
                  enum:
                    - eastus
                    - westus2
                    - westeurope
                    - northeurope
                    - southeastasia
                  default: eastus
                azureSubscriptionId:
                  title: Azure Subscription ID
                  type: string

    - title: GCP Configuration
      dependencies:
        cloudProvider:
          oneOf:
            - properties:
                cloudProvider:
                  const: gcp
                gcpRegion:
                  title: GCP Region
                  type: string
                  enum:
                    - us-central1
                    - us-east1
                    - europe-west1
                    - europe-west2
                    - asia-east1
                  default: us-central1
                gcpProjectId:
                  title: GCP Project ID
                  type: string

    - title: Cluster Configuration
      properties:
        kubernetesVersion:
          title: Kubernetes Version
          type: string
          enum:
            - '1.29'
            - '1.28'
            - '1.27'
          default: '1.29'
        nodePoolConfig:
          title: Node Pool Configuration
          type: object
          properties:
            minNodes:
              title: Minimum Nodes
              type: number
              default: 3
            maxNodes:
              title: Maximum Nodes
              type: number
              default: 10
            nodeSize:
              title: Node Size
              type: string
              enum:
                - small
                - medium
                - large
              enumNames:
                - Small (2 vCPU, 4GB)
                - Medium (4 vCPU, 16GB)
                - Large (8 vCPU, 32GB)
              default: medium

    - title: Platform Components
      properties:
        enableGitOps:
          title: Enable GitOps (ArgoCD)
          type: boolean
          default: true
          description: Install ArgoCD for GitOps-based deployments
        enableObservability:
          title: Enable Observability Stack
          type: boolean
          default: true
          description: Install Prometheus, Grafana, and Loki
        enableServiceMesh:
          title: Enable Service Mesh (Istio)
          type: boolean
          default: false
          description: Install Istio service mesh
        enableCertManager:
          title: Enable Cert-Manager
          type: boolean
          default: true
          description: Install cert-manager for TLS certificate management
        enableExternalDns:
          title: Enable External-DNS
          type: boolean
          default: true
          description: Install external-dns for automatic DNS management
        enableIngress:
          title: Enable Ingress Controller
          type: string
          enum:
            - nginx
            - traefik
            - none
          default: nginx

    - title: Security Configuration
      properties:
        enablePodSecurityPolicies:
          title: Enable Pod Security Standards
          type: boolean
          default: true
        enableNetworkPolicies:
          title: Enable Network Policies
          type: boolean
          default: true
        enableOPA:
          title: Enable OPA/Gatekeeper
          type: boolean
          default: false
          description: Install OPA Gatekeeper for policy enforcement
        enableVaultIntegration:
          title: Enable HashiCorp Vault Integration
          type: boolean
          default: false

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectName: ${{ parameters.projectName }}
          environment: ${{ parameters.environment }}
          cloudProvider: ${{ parameters.cloudProvider }}
          awsRegion: ${{ parameters.awsRegion }}
          azureRegion: ${{ parameters.azureRegion }}
          azureSubscriptionId: ${{ parameters.azureSubscriptionId }}
          gcpRegion: ${{ parameters.gcpRegion }}
          gcpProjectId: ${{ parameters.gcpProjectId }}
          kubernetesVersion: ${{ parameters.kubernetesVersion }}
          nodePoolConfig: ${{ parameters.nodePoolConfig }}
          enableGitOps: ${{ parameters.enableGitOps }}
          enableObservability: ${{ parameters.enableObservability }}
          enableServiceMesh: ${{ parameters.enableServiceMesh }}
          enableCertManager: ${{ parameters.enableCertManager }}
          enableExternalDns: ${{ parameters.enableExternalDns }}
          enableIngress: ${{ parameters.enableIngress }}
          enablePodSecurityPolicies: ${{ parameters.enablePodSecurityPolicies }}
          enableNetworkPolicies: ${{ parameters.enableNetworkPolicies }}
          enableOPA: ${{ parameters.enableOPA }}
          enableVaultIntegration: ${{ parameters.enableVaultIntegration }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: Kubernetes Platform Infrastructure for ${{ parameters.projectName }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
