apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apache-kafka
  title: Apache Kafka
  description: Distributed event streaming platform
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - kafka
    - streaming
spec:
  type: service
  lifecycle: production
  owner: data-team
  system: data-services-platform
  providesApis:
    - kafka-api
