apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-lambda
  title: AWS Lambda Function
  description: Create an AWS Lambda function with IAM role, CloudWatch logs, and optional VPC configuration
  tags:
    - terraform
    - aws
    - lambda
    - serverless
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Lambda Configuration
      required:
        - name
        - owner
        - aws_region
        - environment
        - runtime
      properties:
        name:
          title: Function Name
          type: string
          pattern: '^[a-z0-9-]+$'
        description:
          title: Description
          type: string
          description: Description of the Lambda function
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        aws_region:
          title: AWS Region
          type: string
          default: us-east-1
          enum: [us-east-1, us-east-2, us-west-2, eu-west-1, eu-central-1]
        environment:
          title: Environment
          type: string
          default: dev
          enum: [dev, staging, prod]
        runtime:
          title: Runtime
          type: string
          default: python3.12
          enum:
            [
              python3.12,
              python3.11,
              nodejs20.x,
              nodejs18.x,
              go1.x,
              java21,
              java17,
            ]
        handler:
          title: Handler
          type: string
          description: Lambda function handler (e.g., main.handler)
          default: 'main.handler'
        memory_size:
          title: Memory (MB)
          type: integer
          default: 256
          enum: [128, 256, 512, 1024, 2048]
        timeout:
          title: Timeout (seconds)
          type: integer
          default: 30

    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          aws_region: ${{ parameters.aws_region }}
          environment: ${{ parameters.environment }}
          runtime: ${{ parameters.runtime }}
          handler: ${{ parameters.handler }}
          memory_size: ${{ parameters.memory_size }}
          timeout: ${{ parameters.timeout }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'AWS Lambda - ${{ parameters.name }}'
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
