apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-three-tier-webapp
  title: GCP 3-Tier Web Application
  description: Production-ready 3-tier architecture with Cloud Load Balancer, GKE/MIG, and Cloud SQL on GCP
  tags:
    - gcp
    - three-tier
    - web-app
    - production-ready
    - terraform
    - recommended
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Project Configuration
      required:
        - projectName
        - environment
        - gcpProjectId
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name for the project (lowercase, hyphens allowed)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          enum:
            - dev
            - staging
            - production
          default: dev
        gcpProjectId:
          title: GCP Project ID
          type: string
          description: Your GCP project ID
        region:
          title: GCP Region
          type: string
          enum:
            - us-central1
            - us-east1
            - us-west1
            - europe-west1
            - europe-west2
            - asia-east1
            - asia-southeast1
          default: us-central1

    - title: Network Configuration
      properties:
        vpcCidr:
          title: VPC CIDR Block
          type: string
          default: '10.0.0.0/16'
          description: Primary CIDR range for the VPC

    - title: Compute Configuration
      required:
        - computeType
      properties:
        computeType:
          title: Compute Type
          type: string
          enum:
            - gke-autopilot
            - gke-standard
            - mig
          enumNames:
            - GKE Autopilot (Serverless)
            - GKE Standard
            - Managed Instance Group
          default: gke-autopilot
        machineType:
          title: Machine Type
          type: string
          default: e2-medium
          description: GCE machine type (for GKE Standard or MIG)
        minNodes:
          title: Minimum Nodes
          type: number
          default: 2
        maxNodes:
          title: Maximum Nodes
          type: number
          default: 10

    - title: Database Configuration
      required:
        - databaseEngine
      properties:
        databaseEngine:
          title: Database Engine
          type: string
          enum:
            - POSTGRES
            - MYSQL
          enumNames:
            - PostgreSQL
            - MySQL
          default: POSTGRES
        databaseTier:
          title: Database Tier
          type: string
          default: db-custom-2-4096
          description: Cloud SQL machine tier
        highAvailability:
          title: Enable High Availability
          type: boolean
          default: true

    - title: Security & CDN
      properties:
        enableCloudArmor:
          title: Enable Cloud Armor
          type: boolean
          default: true
          description: Enable Cloud Armor WAF for DDoS protection
        enableCloudCdn:
          title: Enable Cloud CDN
          type: boolean
          default: false
          description: Enable Cloud CDN for global content delivery

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: '.j2'
        values:
          projectName: ${{ parameters.projectName }}
          environment: ${{ parameters.environment }}
          gcpProjectId: ${{ parameters.gcpProjectId }}
          region: ${{ parameters.region }}
          vpcCidr: ${{ parameters.vpcCidr }}
          computeType: ${{ parameters.computeType }}
          machineType: ${{ parameters.machineType }}
          minNodes: ${{ parameters.minNodes }}
          maxNodes: ${{ parameters.maxNodes }}
          databaseEngine: ${{ parameters.databaseEngine }}
          databaseTier: ${{ parameters.databaseTier }}
          highAvailability: ${{ parameters.highAvailability }}
          enableCloudArmor: ${{ parameters.enableCloudArmor }}
          enableCloudCdn: ${{ parameters.enableCloudCdn }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: GCP 3-Tier Infrastructure for ${{ parameters.projectName }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
