#!/bin/bash

# AWX Deployment Script
# Generated by AWX Backstage Platform

set -euo pipefail

# Configuration
AWX_NAME="${{ values.name }}"
NAMESPACE="${{ values.namespace }}"
ENVIRONMENT="${{ values.environment }}"
{%- if values.ingress_enabled %}
HOSTNAME="${{ values.hostname }}"
{%- endif %}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check kubectl
    if ! command -v kubectl &> /dev/null; then
        log_error "kubectl is required but not installed"
        exit 1
    fi
    
    # Check cluster connection
    if ! kubectl cluster-info &> /dev/null; then
        log_error "Cannot connect to Kubernetes cluster"
        exit 1
    fi
    
    # Check AWX operator
    if ! kubectl get crd awxs.awx.ansible.com &> /dev/null; then
        log_error "AWX operator is not installed in the cluster"
        log_info "Please install AWX operator first:"
        log_info "kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml"
        exit 1
    fi
    
    log_info "Prerequisites check passed"
}

# Deploy AWX
deploy_awx() {
    log_info "Deploying AWX instance: $AWX_NAME in namespace: $NAMESPACE"
    
    # Apply Kubernetes manifests
    kubectl apply -k k8s/
    
    log_info "AWX deployment initiated"
    log_info "Waiting for AWX to be ready..."
    
    # Wait for AWX to be ready
    timeout=600  # 10 minutes
    while [ $timeout -gt 0 ]; do
        if kubectl get awx $AWX_NAME -n $NAMESPACE -o jsonpath='{.status.conditions[?(@.type=="Running")].status}' 2>/dev/null | grep -q "True"; then
            log_info "AWX is running!"
            break
        fi
        echo -n "."
        sleep 10
        timeout=$((timeout - 10))
    done
    
    if [ $timeout -le 0 ]; then
        log_error "Timeout waiting for AWX to be ready"
        exit 1
    fi
}

# Display access information
show_access_info() {
    log_info "AWX Deployment completed successfully!"
    echo
    log_info "Access Information:"
    
    {%- if values.ingress_enabled %}
    echo "  Web Interface: https://$HOSTNAME"
    {%- elif values.service_type == 'NodePort' %}
    NODE_PORT=$(kubectl get service awx-$AWX_NAME-service -n $NAMESPACE -o jsonpath='{.spec.ports[0].nodePort}')
    NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
    if [ -z "$NODE_IP" ]; then
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
    fi
    echo "  Web Interface: http://$NODE_IP:$NODE_PORT"
    {%- else %}
    echo "  Service Type: ClusterIP (internal access only)"
    echo "  To access externally, use port forwarding:"
    echo "    kubectl port-forward -n $NAMESPACE svc/awx-$AWX_NAME-service 8080:80"
    echo "  Then access: http://localhost:8080"
    {%- endif %}
    
    # Get admin password
    ADMIN_PASSWORD=$(kubectl get secret awx-$AWX_NAME-admin-password -n $NAMESPACE -o jsonpath='{.data.password}' | base64 -d)
    echo "  Username: ${{ values.admin_user }}"
    echo "  Password: $ADMIN_PASSWORD"
    echo
    
    log_warn "Security Notice:"
    log_warn "- Change the default admin password immediately"
    log_warn "- Update database passwords in production"
    log_warn "- Configure proper TLS certificates"
    {%- if values.environment == 'production' %}
    log_warn "- Review and adjust resource limits for production workloads"
    {%- endif %}
}

# Show status
show_status() {
    log_info "AWX Status:"
    kubectl get awx $AWX_NAME -n $NAMESPACE
    echo
    
    log_info "Pods:"
    kubectl get pods -n $NAMESPACE -l app.kubernetes.io/instance=$AWX_NAME
    echo
    
    log_info "Services:"
    kubectl get services -n $NAMESPACE -l app.kubernetes.io/instance=$AWX_NAME
    echo
    
    {%- if values.ingress_enabled %}
    log_info "Ingress:"
    kubectl get ingress -n $NAMESPACE -l app.kubernetes.io/instance=$AWX_NAME
    echo
    {%- endif %}
}

# Main function
main() {
    case "${1:-deploy}" in
        "deploy")
            check_prerequisites
            deploy_awx
            show_access_info
            ;;
        "status")
            show_status
            ;;
        "delete")
            log_warn "Deleting AWX instance: $AWX_NAME"
            read -p "Are you sure? This will delete all AWX data! (y/N): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                kubectl delete -k k8s/
                log_info "AWX instance deleted"
            else
                log_info "Deletion cancelled"
            fi
            ;;
        "logs")
            kubectl logs -n $NAMESPACE -l app.kubernetes.io/instance=$AWX_NAME --tail=100 -f
            ;;
        *)
            echo "Usage: $0 [deploy|status|delete|logs]"
            echo "  deploy  - Deploy AWX instance (default)"
            echo "  status  - Show AWX status"
            echo "  delete  - Delete AWX instance"
            echo "  logs    - Show AWX logs"
            exit 1
            ;;
    esac
}

main "$@"
