apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fullstack-ecommerce
  title: Full-Stack E-Commerce Platform
  description: Create a complete e-commerce platform with React frontend, Node.js backend, database, and full cloud infrastructure
  tags:
    - recommended
    - fullstack
    - ecommerce
    - react
    - nodejs
    - terraform
    - production-ready
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Project Information
      required:
        - projectName
        - environment
        - businessUnit
        - description
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name of the e-commerce project (e.g., acme-store)
          pattern: '^[a-z0-9\-]+$'
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          description: Deployment environment
          enum:
            - dev
            - stg
            - prod
          enumNames:
            - Development
            - Staging
            - Production
        businessUnit:
          title: Business Unit
          type: string
          enum:
            - engineering
            - platform
            - ecommerce
            - retail
          enumNames:
            - Engineering
            - Platform Engineering
            - E-Commerce Team
            - Retail Operations
        description:
          title: Description
          type: string
          description: Description of the e-commerce platform

    - title: Cloud Provider & Region
      required:
        - provider
        - region
      properties:
        provider:
          title: Cloud Provider
          type: string
          description: Cloud provider for infrastructure
          enum:
            - azure
            - aws
            - gcp
          enumNames:
            - Microsoft Azure
            - Amazon Web Services
            - Google Cloud Platform
        region:
          title: Primary Region
          type: string
          description: Primary deployment region
          default: eastus
        enableMultiRegion:
          title: Enable Multi-Region
          type: boolean
          description: Deploy to multiple regions (production only)
          default: false

    - title: Platform Features
      properties:
        enableCMS:
          title: CMS for Products
          type: boolean
          description: Include headless CMS for product management
          default: true
        enablePayments:
          title: Payment Integration
          type: boolean
          description: Include payment gateway integration
          default: true
        enableSearch:
          title: Search Service
          type: boolean
          description: Include Elasticsearch/Algolia for product search
          default: true
        enableReviews:
          title: Product Reviews
          type: boolean
          description: Include customer review system
          default: true
        enableInventory:
          title: Inventory Management
          type: boolean
          description: Include inventory tracking
          default: true
        enableAnalytics:
          title: Analytics Dashboard
          type: boolean
          description: Include analytics and reporting dashboard
          default: true

    - title: Scalability & Performance
      properties:
        enableCDN:
          title: CDN for Static Assets
          type: boolean
          description: Use CDN for images and static content
          default: true
        enableCaching:
          title: Redis Cache
          type: boolean
          description: Include Redis for caching
          default: true
        autoScaling:
          title: Auto-Scaling
          type: boolean
          description: Enable auto-scaling for frontend and backend
          default: true

  steps:
    - id: fetch-infra
      name: Fetch Infrastructure
      action: fetch:template
      input:
        url: ./skeleton/infra
        targetPath: ./infra
        values:
          projectName: ${{ parameters.projectName }}
          environment: ${{ parameters.environment }}
          businessUnit: ${{ parameters.businessUnit }}
          description: ${{ parameters.description }}
          provider: ${{ parameters.provider }}
          region: ${{ parameters.region }}
          enableMultiRegion: ${{ parameters.enableMultiRegion }}

    - id: fetch-backend
      name: Fetch Backend API
      action: fetch:template
      input:
        url: ./skeleton/backend
        targetPath: ./backend
        values:
          projectName: ${{ parameters.projectName }}
          environment: ${{ parameters.environment }}
          projectDescription: ${{ parameters.description }}
          enableCMS: ${{ parameters.enableCMS }}
          enablePayments: ${{ parameters.enablePayments }}
          enableSearch: ${{ parameters.enableSearch }}
          enableReviews: ${{ parameters.enableReviews }}
          enableInventory: ${{ parameters.enableInventory }}
          enableAnalytics: ${{ parameters.enableAnalytics }}
          enableCaching: ${{ parameters.enableCaching }}
          apiBasePath: '/api/v1'

    - id: fetch-frontend
      name: Fetch Frontend App
      action: fetch:template
      input:
        url: ./skeleton/frontend
        targetPath: ./frontend
        values:
          projectName: ${{ parameters.projectName }}
          appTitle: ${{ parameters.projectName | capitalize }} Store
          apiBaseUrl: '/api/v1'
          enableCMS: ${{ parameters.enableCMS }}
          enablePayments: ${{ parameters.enablePayments }}
          enableAnalytics: ${{ parameters.enableAnalytics }}
          enableCDN: ${{ parameters.enableCDN }}

    - id: publish
      name: Publish to Repository
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitCommitMessage: 'feat: initial commit - e-commerce platform'

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - id: create-comment
      name: Post-Generation Instructions
      action: debug:log
      input:
        message: |
          🎉 E-Commerce Platform Created Successfully!

          Next Steps:
          1. Configure your cloud provider credentials
          2. cd infra && terraform init
          3. terraform plan -var-file=environments/${{ parameters.environment }}.tfvars
          4. terraform apply -var-file=environments/${{ parameters.environment }}.tfvars
          5. cd ../backend && npm install && npm run dev
          6. cd ../frontend && npm install && npm run dev

          Access your store at: http://localhost:3000
          API docs at: http://localhost:8080/api-docs

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Store Frontend
        url: http://localhost:3000
        icon: storefront
      - title: API Documentation
        url: http://localhost:8080/api-docs
        icon: docs
