version: 2

sources:
  - name: raw
    description: Raw data source tables
    database: "{{ var('raw_database', 'raw') }}"
    schema: "{{ var('raw_schema', 'raw') }}"
    tables:
      - name: example_table
        description: Example source table
        columns:
          - name: id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: created_at
            description: Timestamp when record was created
          - name: updated_at
            description: Timestamp when record was last updated
