apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-vpc
  title: AWS VPC Module
  description: Terraform module for creating AWS VPCs with subnets, NAT gateways, security groups, and network ACLs
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    backstage.io/source-location: url:https://github.com/company/terraform-modules
    backstage.io/view-url: https://github.com/company/terraform-modules
    backstage.io/edit-url: https://github.com/company/terraform-modules/edit/main/aws-vpc.yaml
  tags:
    - terraform
    - aws
    - vpc
    - network
    - infrastructure
  links:
    - url: https://docs.aws.amazon.com/vpc/
      title: AWS VPC Documentation
      icon: docs
    - url: https://registry.terraform.io
      title: Terraform Registry
      icon: code
spec:
  type: library
  lifecycle: production
  owner: platform-team
  system: infrastructure-as-code-platform
  dependsOn:
    - component:terraform-modules
