apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-vnet
  title: Azure VNet Module
  description: Terraform module for creating Azure Virtual Networks with subnets, NSGs, and peering
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    backstage.io/source-location: url:https://github.com/company/terraform-modules
    backstage.io/view-url: https://github.com/company/terraform-modules
    backstage.io/edit-url: https://github.com/company/terraform-modules/edit/main/azure-vnet.yaml
  tags:
    - terraform
    - azure
    - vnet
    - network
    - infrastructure
  links:
    - url: https://docs.microsoft.com/azure/virtual-network/
      title: Azure VNet Documentation
      icon: docs
    - url: https://registry.terraform.io
      title: Terraform Registry
      icon: code
spec:
  type: library
  lifecycle: production
  owner: platform-team
  system: infrastructure-as-code-platform
  dependsOn:
    - component:terraform-modules
