apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-modules
  title: Terraform Modules Library
  description: |
    Centralized library of reusable Terraform modules for Azure, AWS, and GCP.
    Includes shared modules for naming, tagging, and validation.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: containercode/terraform-modules
  tags:
    - terraform
    - iac
    - azure
    - aws
    - gcp
    - modules
  links:
    - url: https://registry.terraform.io
      title: Terraform Registry
      icon: dashboard
spec:
  type: library
  lifecycle: production
  owner: platform-team
  system: cloud-infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: terraform-shared-modules
  title: Shared Terraform Modules
  description: Cross-provider shared modules for naming, tagging, and validation
  tags:
    - terraform
    - shared
spec:
  type: module-library
  owner: platform-team
  system: cloud-infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: terraform-azure-modules
  title: Azure Terraform Modules
  description: Azure-specific Terraform modules (VNet, AKS, Storage, Key Vault, SQL, etc.)
  tags:
    - terraform
    - azure
spec:
  type: module-library
  owner: platform-team
  system: cloud-infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: terraform-aws-modules
  title: AWS Terraform Modules
  description: AWS-specific Terraform modules (VPC, EKS, S3, RDS, etc.)
  tags:
    - terraform
    - aws
spec:
  type: module-library
  owner: platform-team
  system: cloud-infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: terraform-gcp-modules
  title: GCP Terraform Modules
  description: GCP-specific Terraform modules (VPC, GKE, Cloud Storage, Cloud SQL, etc.)
  tags:
    - terraform
    - gcp
spec:
  type: module-library
  owner: platform-team
  system: cloud-infrastructure
---
# Location to discover all AWS module catalog entries
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-aws-module-catalog
  description: AWS Terraform module catalog entries
spec:
  type: file
  targets:
    - ./aws/resources/compute/*/catalog-info.yaml
    - ./aws/resources/containers/*/catalog-info.yaml
    - ./aws/resources/core/*/catalog-info.yaml
    - ./aws/resources/database/*/catalog-info.yaml
    - ./aws/resources/kubernetes/*/catalog-info.yaml
    - ./aws/resources/messaging/*/catalog-info.yaml
    - ./aws/resources/monitoring/*/catalog-info.yaml
    - ./aws/resources/network/*/catalog-info.yaml
    - ./aws/resources/security/*/catalog-info.yaml
    - ./aws/resources/storage/*/catalog-info.yaml
---
# Location to discover all Azure module catalog entries
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-azure-module-catalog
  description: Azure Terraform module catalog entries
spec:
  type: file
  targets:
    - ./azure/resources/compute/*/catalog-info.yaml
    - ./azure/resources/containers/*/catalog-info.yaml
    - ./azure/resources/core/*/catalog-info.yaml
    - ./azure/resources/database/*/catalog-info.yaml
    - ./azure/resources/kubernetes/*/catalog-info.yaml
    - ./azure/resources/messaging/*/catalog-info.yaml
    - ./azure/resources/monitoring/*/catalog-info.yaml
    - ./azure/resources/network/*/catalog-info.yaml
    - ./azure/resources/security/*/catalog-info.yaml
    - ./azure/resources/storage/*/catalog-info.yaml
---
# Location to discover all GCP module catalog entries
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-gcp-module-catalog
  description: GCP Terraform module catalog entries
spec:
  type: file
  targets:
    - ./gcp/resources/compute/*/catalog-info.yaml
    - ./gcp/resources/containers/*/catalog-info.yaml
    - ./gcp/resources/core/*/catalog-info.yaml
    - ./gcp/resources/database/*/catalog-info.yaml
    - ./gcp/resources/kubernetes/*/catalog-info.yaml
    - ./gcp/resources/messaging/*/catalog-info.yaml
    - ./gcp/resources/monitoring/*/catalog-info.yaml
    - ./gcp/resources/network/*/catalog-info.yaml
    - ./gcp/resources/security/*/catalog-info.yaml
    - ./gcp/resources/storage/*/catalog-info.yaml
---
# Location to discover all Backstage templates
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-templates-catalog
  description: Terraform infrastructure templates
spec:
  type: file
  targets:
    - ./templates/*/template.yaml
    - ./templates/*/*/template.yaml
