apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: data-dbt
  title: dbt Project
  description: Create a dbt (data build tool) project for data transformation with best practices
  tags:
    - data
    - dbt
    - sql
    - analytics
    - data-engineering
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:data-engineering
  type: service

  parameters:
    - title: Project Information
      required:
        - name
        - owner
      properties:
        name:
          title: Project Name
          type: string
          description: Name of the dbt project
          pattern: '^[a-z][a-z0-9_]*[a-z0-9]$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Purpose of this dbt project
        owner:
          title: Owner
          type: string
          description: Team that owns this resource
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: dbt Configuration
      required:
        - environment
        - warehouse
      properties:
        environment:
          title: Environment
          type: string
          enum:
            - development
            - staging
            - production
          default: development
        warehouse:
          title: Data Warehouse
          type: string
          enum:
            - snowflake
            - bigquery
            - redshift
            - postgres
            - databricks
          default: snowflake
          description: Target data warehouse
        dbtVersion:
          title: dbt Version
          type: string
          enum:
            - "1.7"
            - "1.6"
            - "1.5"
          default: "1.7"

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          environment: ${{ parameters.environment }}
          warehouse: ${{ parameters.warehouse }}
          dbtVersion: ${{ parameters.dbtVersion }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: 'dbt Project: ${{ parameters.name }}'
        repoVisibility: private
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
