apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-module-template
  title: Terraform Module
  description: Create a production-ready Terraform module with best practices for AWS, Azure, or GCP
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - recommended
    - terraform
    - infrastructure-as-code
    - aws
    - azure
    - gcp
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Module Information
      required:
        - name
        - description
        - owner
        - provider
      properties:
        name:
          title: Module Name
          type: string
          description: Name of the Terraform module
          pattern: '^terraform-[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Must start with "terraform-" and use lowercase letters, numbers, and hyphens'
        description:
          title: Description
          type: string
          description: Brief description of what this module provisions
        owner:
          title: Owner
          type: string
          description: Owner of the module
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        provider:
          title: Cloud Provider
          type: string
          description: Select the cloud provider for this module
          default: aws
          enum:
            - aws
            - azure
            - gcp
            - multi-cloud
          enumNames:
            - Amazon Web Services
            - Microsoft Azure
            - Google Cloud Platform
            - Multi-Cloud (All Providers)
          ui:widget: radio
    - title: Repository Information
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
    - title: Configuration Options
      properties:
        terraform_version:
          title: Terraform Version Constraint
          type: string
          description: Minimum Terraform version required
          default: '>= 1.5'
          enum:
            - '>= 1.0'
            - '>= 1.3'
            - '>= 1.5'
            - '>= 1.6'
  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          provider: ${{ parameters.provider }}
          terraform_version: ${{ parameters.terraform_version }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
        # Copy without templating: files that contain || operators or other
        # syntax that conflicts with Nunjucks template parsing
        copyWithoutTemplating:
          - '**/*.sh'
          - '**/*.tpl'
          - '**/cloud-init.yaml'
          - '.github/workflows/**'
          # Provider submodule .tf files contain || operators that break Nunjucks
          - 'aws/**/*.tf'
          - 'azure/**/*.tf'
          - 'gcp/**/*.tf'
          - 'examples/**/*.tf'

    - id: remove-aws
      name: Remove AWS folder (not selected)
      if: ${{ parameters.provider !== 'aws' and parameters.provider !== 'multi-cloud' }}
      action: fs:delete
      input:
        files:
          - aws

    - id: remove-azure
      name: Remove Azure folder (not selected)
      if: ${{ parameters.provider !== 'azure' and parameters.provider !== 'multi-cloud' }}
      action: fs:delete
      input:
        files:
          - azure

    - id: remove-gcp
      name: Remove GCP folder (not selected)
      if: ${{ parameters.provider !== 'gcp' and parameters.provider !== 'multi-cloud' }}
      action: fs:delete
      input:
        files:
          - gcp

    - id: publish
      name: Publish to Repository
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitCommitMessage: 'Initial commit: ${{ parameters.name }} Terraform module'
        gitAuthorName: 'DevOps Backstage'
        gitAuthorEmail: 'backstage@devops.company.com'
        topics:
          - terraform
          - infrastructure-as-code
          - ${{ parameters.provider }}

    - id: register
      name: Register in Software Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: Next Steps
        content: |
          ## Your Terraform module has been created!

          ### Getting Started
          1. Clone the repository
          2. Copy `terraform.tfvars.example` to `terraform.tfvars`
          3. Update the values for your environment
          4. Run `terraform init` and `terraform plan`

          ### Module Structure
          Your module includes pre-configured resources for:
          - **Compute** - Virtual machines and auto-scaling
          - **Network** - VPC/VNet, subnets, NAT
          - **Storage** - Object and file storage
          - **Database** - Managed databases and caching
          - **Security** - KMS, secrets, IAM
          - **Observability** - Monitoring and alerting
          - **Kubernetes** - Managed K8s clusters
          - **Serverless** - Functions and API gateways

          Enable/disable modules using feature flags in `terraform.tfvars`.
