apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: automation-platform
  title: Automation Platform
  description: Infrastructure automation and orchestration domain
spec:
  owner: awx-team
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: infrastructure
  title: Infrastructure
  description: Core infrastructure and deployment automation
spec:
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: devops
  title: DevOps
  description: Development operations and CI/CD automation
spec:
  owner: devops-team
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: cloud-sandbox
  title: Cloud Sandbox
  description: Cloud development environments and sandbox infrastructure
spec:
  owner: platform-team
