apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus-stack
  title: Prometheus Monitoring Stack
  description: Prometheus, Grafana, and AlertManager for metrics and monitoring
  annotations:
    prometheus.io/server-url: https://prometheus.company.com
    grafana.com/dashboard-url: https://grafana.company.com
  tags:
    - prometheus
    - grafana
    - alertmanager
    - monitoring
    - metrics
spec:
  type: service
  lifecycle: production
  owner: sre-team
  system: observability-platform
  providesApis:
    - prometheus-api
    - grafana-api
  dependsOn:
    - resource:prometheus-storage
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elk-stack
  title: ELK Stack (Elasticsearch, Logstash, Kibana)
  description: Centralized logging and log analysis platform
  annotations:
    elasticsearch.elastic.co/cluster-url: https://elasticsearch.company.com
    kibana.elastic.co/dashboard-url: https://kibana.company.com
  tags:
    - elasticsearch
    - logstash
    - kibana
    - logging
    - search
    - analytics
spec:
  type: service
  lifecycle: production
  owner: sre-team
  system: observability-platform
  providesApis:
    - elasticsearch-api
    - kibana-api
  dependsOn:
    - resource:elasticsearch-cluster
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jaeger-tracing
  title: Jaeger Distributed Tracing
  description: Distributed tracing and performance monitoring
  annotations:
    jaegertracing.io/collector-url: https://jaeger-collector.company.com
    jaegertracing.io/query-url: https://jaeger.company.com
  tags:
    - jaeger
    - tracing
    - performance
    - distributed-systems
    - observability
spec:
  type: service
  lifecycle: production
  owner: sre-team
  system: observability-platform
  providesApis:
    - jaeger-api
  dependsOn:
    - resource:jaeger-storage
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: datadog-integration
  title: Datadog Monitoring Integration
  description: Datadog APM, infrastructure monitoring, and log management
  annotations:
    datadoghq.com/api-url: https://api.datadoghq.com
    datadoghq.com/app-url: https://app.datadoghq.com
  tags:
    - datadog
    - apm
    - infrastructure-monitoring
    - log-management
    - synthetic-monitoring
spec:
  type: service
  lifecycle: production
  owner: sre-team
  system: observability-platform
  providesApis:
    - datadog-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-relic-integration
  title: New Relic Monitoring
  description: Application performance monitoring and observability
  annotations:
    newrelic.com/api-url: https://api.newrelic.com
    newrelic.com/app-url: https://one.newrelic.com
  tags:
    - new-relic
    - apm
    - monitoring
    - alerts
    - dashboards
spec:
  type: service
  lifecycle: production
  owner: sre-team
  system: observability-platform
  providesApis:
    - newrelic-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: splunk-enterprise
  title: Splunk Enterprise
  description: Machine data analytics and security monitoring
  annotations:
    splunk.com/server-url: https://splunk.company.com
  tags:
    - splunk
    - machine-data
    - analytics
    - security
    - siem
spec:
  type: service
  lifecycle: production
  owner: security-team
  system: observability-platform
  providesApis:
    - splunk-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pagerduty-integration
  title: PagerDuty Incident Management
  description: Incident response and on-call management
  annotations:
    pagerduty.com/service-url: https://company.pagerduty.com
  tags:
    - pagerduty
    - incident-management
    - on-call
    - alerts
    - escalation
spec:
  type: service
  lifecycle: production
  owner: sre-team
  system: observability-platform
  providesApis:
    - pagerduty-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: prometheus-api
  title: Prometheus API
  description: Prometheus query API for metrics retrieval
  tags:
    - prometheus
    - metrics
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Prometheus API
      version: '1.0.0'
    paths:
      /api/v1/query:
        get:
          summary: Execute instant query
          parameters:
            - name: query
              in: query
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Query result
      /api/v1/query_range:
        get:
          summary: Execute range query
          responses:
            '200':
              description: Range query result
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: grafana-api
  title: Grafana API
  description: Grafana dashboard and administration API
  tags:
    - grafana
    - dashboards
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Grafana API
      version: '10.0.0'
    paths:
      /api/dashboards:
        get:
          summary: List dashboards
          responses:
            '200':
              description: Dashboard list
      /api/dashboards/{uid}:
        get:
          summary: Get dashboard by UID
          parameters:
            - name: uid
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Dashboard details
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: elasticsearch-api
  title: Elasticsearch API
  description: Elasticsearch search and indexing API
  tags:
    - elasticsearch
    - search
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Elasticsearch API
      version: '8.8.0'
    paths:
      /_search:
        post:
          summary: Search across indices
          responses:
            '200':
              description: Search results
      /{index}/_search:
        post:
          summary: Search within index
          parameters:
            - name: index
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Search results
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kibana-api
  title: Kibana API
  description: Kibana visualization and dashboard API
  tags:
    - kibana
    - visualization
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Kibana API
      version: '8.8.0'
    paths:
      /api/saved_objects/_find:
        get:
          summary: Find saved objects
          responses:
            '200':
              description: Saved objects list
      /api/dashboards/dashboard/{id}:
        get:
          summary: Get dashboard
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Dashboard details
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jaeger-api
  title: Jaeger API
  description: Jaeger tracing query API
  tags:
    - jaeger
    - tracing
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Jaeger API
      version: '1.0.0'
    paths:
      /api/traces:
        get:
          summary: Search traces
          parameters:
            - name: service
              in: query
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Trace list
      /api/traces/{traceId}:
        get:
          summary: Get trace by ID
          parameters:
            - name: traceId
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Trace details
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: datadog-api
  title: Datadog API
  description: Datadog monitoring and APM API
  tags:
    - datadog
    - monitoring
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Datadog API
      version: '1.0.0'
    paths:
      /api/v1/metrics:
        get:
          summary: Query metrics
          responses:
            '200':
              description: Metrics data
      /api/v1/events:
        get:
          summary: Query events
          responses:
            '200':
              description: Events list
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: newrelic-api
  title: New Relic API
  description: New Relic monitoring API
  tags:
    - new-relic
    - monitoring
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: New Relic API
      version: '2.0.0'
    paths:
      /v2/applications.json:
        get:
          summary: List applications
          responses:
            '200':
              description: Application list
      /v2/applications/{id}/metrics.json:
        get:
          summary: Get application metrics
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
          responses:
            '200':
              description: Metrics data
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: splunk-api
  title: Splunk API
  description: Splunk search and data API
  tags:
    - splunk
    - search
    - api
spec:
  type: openapi
  lifecycle: production
  owner: security-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Splunk API
      version: '9.0.0'
    paths:
      /services/search/jobs:
        post:
          summary: Create search job
          responses:
            '201':
              description: Search job created
      /services/search/jobs/{sid}/results:
        get:
          summary: Get search results
          parameters:
            - name: sid
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Search results
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pagerduty-api
  title: PagerDuty API
  description: PagerDuty incident management API
  tags:
    - pagerduty
    - incident
    - api
spec:
  type: openapi
  lifecycle: production
  owner: sre-team
  system: observability-platform
  definition: |
    openapi: 3.0.0
    info:
      title: PagerDuty API
      version: '2.0.0'
    paths:
      /incidents:
        get:
          summary: List incidents
          responses:
            '200':
              description: Incident list
        post:
          summary: Create incident
          responses:
            '201':
              description: Incident created
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: prometheus-storage
  title: Prometheus Storage
  description: Time-series database storage for Prometheus
  tags:
    - storage
    - time-series
    - prometheus
spec:
  type: storage
  owner: platform-team
  system: observability-platform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elasticsearch-cluster
  title: Elasticsearch Cluster
  description: Elasticsearch cluster for log storage and search
  tags:
    - elasticsearch
    - cluster
    - search
spec:
  type: cluster
  owner: platform-team
  system: observability-platform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jaeger-storage
  title: Jaeger Storage Backend
  description: Storage backend for Jaeger traces
  tags:
    - jaeger
    - storage
    - tracing
spec:
  type: storage
  owner: platform-team
  system: observability-platform
