apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: packer-image-template
  title: Packer Machine Image
  description: Create machine images for AWS, Azure, GCP, or VMware with Packer
  tags:
    - packer
    - image
    - ami
    - cloud
spec:
  owner: platform-team
  type: resource
  parameters:
    - title: Basic Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          pattern: '^([a-z0-9\-])+$'
          ui:autofocus: true
        description:
          title: Description
          type: string
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
    - title: Image Configuration
      required:
        - cloud_provider
        - base_os
      properties:
        cloud_provider:
          title: Cloud Provider
          type: string
          default: aws
          enum:
            - aws
            - azure
            - gcp
            - vmware
          enumNames:
            - AWS (AMI)
            - Azure (Managed Image)
            - GCP (Compute Image)
            - VMware (OVA/OVF)
        base_os:
          title: Base OS
          type: string
          default: ubuntu-22.04
          enum:
            - ubuntu-22.04
            - ubuntu-20.04
            - amazon-linux-2023
            - rhel-9
            - debian-12
            - windows-2022
        region:
          title: Region
          type: string
          default: us-east-1
        instance_type:
          title: Instance Type
          type: string
          default: t3.medium
    - title: Provisioning
      properties:
        install_docker:
          title: Install Docker
          type: boolean
          default: true
        install_ansible:
          title: Install Ansible
          type: boolean
          default: false
        custom_packages:
          title: Additional Packages
          type: array
          items:
            type: string
          default:
            - curl
            - wget
            - git
    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          cloud_provider: ${{ parameters.cloud_provider }}
          base_os: ${{ parameters.base_os }}
          region: ${{ parameters.region }}
          instance_type: ${{ parameters.instance_type }}
          install_docker: ${{ parameters.install_docker }}
          install_ansible: ${{ parameters.install_ansible }}
          custom_packages: ${{ parameters.custom_packages }}
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
