apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - azure
    - aks
    - kubernetes
    - ${{ values.environment }}
  links:
    - url: https://portal.azure.com
      title: Azure Portal
      icon: cloud
spec:
  type: kubernetes-cluster
  owner: ${{ values.owner }}
  lifecycle: ${{ values.environment }}
  system: cloud-infrastructure
