apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
{%- if values.enable_metrics %}
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8000'
    prometheus.io/path: '/metrics'
{%- endif %}
  tags:
    - python
    - api
    - ${{ values.framework }}
{%- if values.database_type != 'none' %}
    - ${{ values.database_type }}
{%- endif %}
  links:
    - url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
      title: GitHub Repository
      icon: github
    - url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}/actions
      title: CI/CD Pipeline
      icon: dashboard
{%- if values.enable_docs %}
    - url: https://${{ values.name }}.example.com/api/v1/docs
      title: API Documentation
      icon: docs
{%- endif %}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.name }}-system
  providesApis:
    - ${{ values.name }}-api
{%- if values.database_type == 'postgresql' %}
  dependsOn:
    - resource:default/${{ values.name }}-postgresql
{%- elif values.database_type == 'mysql' %}
  dependsOn:
    - resource:default/${{ values.name }}-mysql
{%- elif values.database_type == 'mongodb' %}
  dependsOn:
    - resource:default/${{ values.name }}-mongodb
{%- endif %}
{%- if values.enable_caching %}
    - resource:default/${{ values.name }}-redis
{%- endif %}

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  description: REST API for ${{ values.name }}
  tags:
    - rest
    - openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  definition: |
    openapi: 3.0.0
    info:
      title: ${{ values.name }} API
      version: 0.1.0
      description: ${{ values.description }}
    servers:
      - url: https://${{ values.name }}.example.com/api/v1
    paths:
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service is healthy
      /items:
        get:
          summary: List items
          responses:
            '200':
              description: List of items
        post:
          summary: Create item
          responses:
            '201':
              description: Item created
