apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - azure
    - functions
    - serverless
    - ${{ values.runtimeStack }}
    - ${{ values.environment }}
  links:
    - url: https://portal.azure.com
      title: Azure Portal
      icon: cloud
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: ${{ values.environment }}
  system: serverless-platform
