apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azurerm-app-insights
  title: Azure Application Insights
  description: |
    Monitoring module for Azure Application Insights.
    Provides production-ready Terraform configuration with best practices.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: containercode/terraform-modules
  tags:
    - terraform
    - azure
    - monitoring
    - app-insights
    - iac
  links:
    - url: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs
      title: Azure Provider Docs
      icon: dashboard
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: cloud-infrastructure
  dependsOn:
    - resource:terraform-azure-modules
