apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
  tags:
    - data
    - superset
    - dashboard
    - analytics
  links:
    - url: https://superset.apache.org/docs/intro
      title: Apache Superset Documentation
      icon: docs
spec:
  type: service
  lifecycle: ${{ values.environment }}
  owner: ${{ values.owner }}
  system: data-platform
