apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-three-tier-webapp
  title: AWS 3-Tier Web Application
  description: Production-ready 3-tier architecture with ALB, ECS/EC2, and RDS on AWS
  tags:
    - aws
    - three-tier
    - web-app
    - production-ready
    - terraform
    - recommended
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Project Configuration
      required:
        - projectName
        - environment
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name for the project (lowercase, hyphens allowed)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          enum:
            - dev
            - staging
            - production
          default: dev
        region:
          title: AWS Region
          type: string
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
            - eu-central-1
            - ap-southeast-1
          default: us-east-1

    - title: Network Configuration
      properties:
        vpcCidr:
          title: VPC CIDR Block
          type: string
          default: '10.0.0.0/16'
          description: CIDR block for the VPC

    - title: Compute Configuration
      required:
        - computeType
      properties:
        computeType:
          title: Compute Type
          type: string
          enum:
            - ecs-fargate
            - ecs-ec2
            - ec2-asg
          enumNames:
            - ECS with Fargate (Serverless)
            - ECS with EC2
            - EC2 Auto Scaling Group
          default: ecs-fargate
        instanceType:
          title: Instance Type
          type: string
          default: t3.medium
          description: EC2 instance type (for ECS-EC2 or ASG)
        minCapacity:
          title: Minimum Capacity
          type: number
          default: 2
        maxCapacity:
          title: Maximum Capacity
          type: number
          default: 10

    - title: Database Configuration
      required:
        - databaseEngine
      properties:
        databaseEngine:
          title: Database Engine
          type: string
          enum:
            - postgres
            - mysql
            - mariadb
          default: postgres
        databaseInstanceClass:
          title: Database Instance Class
          type: string
          default: db.t3.medium
        multiAz:
          title: Enable Multi-AZ
          type: boolean
          default: true

    - title: Security & CDN
      properties:
        enableWaf:
          title: Enable WAF
          type: boolean
          default: true
          description: Enable AWS WAF for web application firewall
        enableCloudfront:
          title: Enable CloudFront
          type: boolean
          default: false
          description: Enable CloudFront CDN for global distribution

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectName: ${{ parameters.projectName }}
          environment: ${{ parameters.environment }}
          region: ${{ parameters.region }}
          vpcCidr: ${{ parameters.vpcCidr }}
          computeType: ${{ parameters.computeType }}
          instanceType: ${{ parameters.instanceType }}
          minCapacity: ${{ parameters.minCapacity }}
          maxCapacity: ${{ parameters.maxCapacity }}
          databaseEngine: ${{ parameters.databaseEngine }}
          databaseInstanceClass: ${{ parameters.databaseInstanceClass }}
          multiAz: ${{ parameters.multiAz }}
          enableWaf: ${{ parameters.enableWaf }}
          enableCloudfront: ${{ parameters.enableCloudfront }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: AWS 3-Tier Infrastructure for ${{ parameters.projectName }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
