apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: google-service-account
  title: GCP Service Account
  description: |
    Core infrastructure module for GCP Service Account.
    Provides production-ready Terraform configuration with best practices.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: containercode/terraform-modules
  tags:
    - terraform
    - gcp
    - core
    - service-account
    - iac
  links:
    - url: https://registry.terraform.io/providers/hashicorp/google/latest/docs
      title: GCP Provider Docs
      icon: dashboard
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: cloud-infrastructure
  dependsOn:
    - resource:terraform-gcp-modules
