apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
    - d2
    - diagrams
spec:
  type: documentation
  lifecycle: production
  owner: ${{ values.owner }}
