apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hugo-static-site-template
  title: Hugo Static Site
  description: Create a Hugo static website for marketing or documentation
  tags:
    - hugo
    - static-site
    - marketing
    - website
spec:
  owner: platform-team
  type: website

  parameters:
    - title: Site Configuration
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Site Name
          type: string
          description: Name for your Hugo site
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the website
        owner:
          title: Owner
          type: string
          description: Owner of this site
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User

    - title: Hugo Configuration
      properties:
        hugoTheme:
          title: Hugo Theme
          type: string
          description: Hugo theme to use
          default: ananke
          enum:
            - ananke
            - papermod
            - terminal
            - minimal
        baseUrl:
          title: Base URL
          type: string
          description: Base URL for the site
          default: https://example.com/

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          hugoTheme: ${{ parameters.hugoTheme }}
          baseUrl: ${{ parameters.baseUrl }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
