apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-s3-bucket
  title: AWS S3 Bucket
  description: Create an S3 bucket with encryption, versioning, and lifecycle policies
  tags:
    - aws
    - s3
    - storage
    - terraform
    - devops
    - data
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:platform-team
  type: infrastructure

  parameters:
    - title: Project Information
      required:
        - name
        - owner
      properties:
        name:
          title: Bucket Name
          type: string
          description: Name of the S3 bucket (will be prefixed with org name)
          pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Purpose of this bucket
        owner:
          title: Owner
          type: string
          description: Team that owns this resource
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Bucket Configuration
      required:
        - environment
        - region
        - orgPrefix
      properties:
        environment:
          title: Environment
          type: string
          enum:
            - development
            - staging
            - production
          default: development
        region:
          title: AWS Region
          type: string
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
            - eu-central-1
            - ap-southeast-1
          default: us-east-1
        orgPrefix:
          title: Organization Prefix
          type: string
          description: Organization prefix for bucket naming (must be globally unique)
          default: 'myorg'
          pattern: '^[a-z0-9-]+$'
        versioning:
          title: Enable Versioning
          type: boolean
          default: true
          description: Enable versioning for object recovery
        encryption:
          title: Encryption Type
          type: string
          enum:
            - AES256
            - aws:kms
          default: AES256
        lifecycleEnabled:
          title: Enable Lifecycle Rules
          type: boolean
          default: false
          description: Enable automatic transition to cheaper storage classes

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: '.j2'
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          environment: ${{ parameters.environment }}
          region: ${{ parameters.region }}
          orgPrefix: ${{ parameters.orgPrefix }}
          versioning: ${{ parameters.versioning }}
          encryption: ${{ parameters.encryption }}
          lifecycleEnabled: ${{ parameters.lifecycleEnabled }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: 'AWS S3 Bucket: ${{ parameters.name }}'
        repoVisibility: private
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
