apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-springboot
  title: Spring Boot API
  description: Create a Spring Boot 3 REST API with Java
  tags:
    - java
    - springboot
    - api
    - backend
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:software-backend
  type: service

  parameters:
    - title: Project Information
      required:
        - name
        - owner
      properties:
        name:
          title: Project Name
          type: string
          description: Name of the Spring Boot application
          pattern: '^[a-z][a-z0-9-]*[a-z0-9]$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Purpose of this API
        owner:
          title: Owner
          type: string
          description: Team that owns this resource
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Application Configuration
      required:
        - environment
        - javaVersion
      properties:
        environment:
          title: Environment
          type: string
          enum:
            - development
            - staging
            - production
          default: development
        javaVersion:
          title: Java Version
          type: string
          enum:
            - '17'
            - '21'
          default: '21'
        serverPort:
          title: Server Port
          type: integer
          default: 8080

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          environment: ${{ parameters.environment }}
          javaVersion: ${{ parameters.javaVersion }}
          serverPort: ${{ parameters.serverPort }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: 'Spring Boot API: ${{ parameters.name }}'
        repoVisibility: private
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
