apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: AWS VPC - ${{ values.environment }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - aws
    - vpc
spec:
  type: infrastructure
  lifecycle: production
  owner: ${{ values.owner }}
