apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azurerm-cosmos-db
  title: Azure Cosmos DB
  description: |
    Database module for Azure Cosmos DB.
    Provides production-ready Terraform configuration with best practices.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: containercode/terraform-modules
  tags:
    - terraform
    - azure
    - database
    - cosmos-db
    - iac
  links:
    - url: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs
      title: Azure Provider Docs
      icon: dashboard
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: cloud-infrastructure
  dependsOn:
    - resource:terraform-azure-modules
