apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apache-airflow
  title: Apache Airflow
  description: Workflow orchestration platform
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - airflow
    - workflow
spec:
  type: service
  lifecycle: production
  owner: data-team
  system: data-platform
  providesApis:
    - airflow-api
