# Development Environment Configuration
# Small resources, aggressive cost optimization

environment_name: 'dev'
description: 'Development environment for testing and development'

# Resource Sizing
sizing:
  vm_size: 'Standard_B2s' # 2 vCPU, 4GB RAM
  disk_type: 'Standard_LRS'
  database_tier: 'Basic'
  cache_tier: 'Basic'
  aks_node_count: 1
  aks_node_size: 'Standard_B2s'

# Cost Optimization
cost_optimization:
  level: 'aggressive'
  auto_shutdown: true
  shutdown_schedule: '0 19 * * 1-5' # weekdays at 7 PM
  spot_instances: true
  reserved_capacity: false

# Monitoring
monitoring:
  level: 'basic'
  metrics_retention_days: 7
  log_retention_days: 7
  alerts_enabled: false
  dashboard_enabled: false

# Security
security:
  network_security: 'standard'
  encryption_required: true
  mfa_required: false
  private_endpoints: false
  firewall_enabled: false

# Networking
networking:
  public_access: true # Easier for development
  vpn_required: false
  bastion_host: false
  private_link: false
