apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-cluster
  title: RabbitMQ Cluster
  description: Message broker for distributed systems
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - rabbitmq
    - messaging
spec:
  type: service
  lifecycle: production
  owner: data-team
  system: data-services-platform
  providesApis:
    - rabbitmq-api
