apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-three-tier-webapp
  title: Azure 3-Tier Web Application
  description: Production-ready 3-tier architecture with Application Gateway, AKS/VMSS, and Azure SQL/PostgreSQL
  tags:
    - azure
    - three-tier
    - web-app
    - production-ready
    - terraform
    - recommended
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Project Configuration
      required:
        - projectName
        - environment
      properties:
        projectName:
          title: Project Name
          type: string
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        environment:
          title: Environment
          type: string
          enum: [dev, staging, production]
          default: dev
        location:
          title: Azure Region
          type: string
          enum: [eastus, westus2, westeurope, northeurope, southeastasia]
          default: eastus

    - title: Network Configuration
      properties:
        vnetAddressSpace:
          title: VNet Address Space
          type: string
          default: '10.0.0.0/16'

    - title: Compute Configuration
      required:
        - computeType
      properties:
        computeType:
          title: Compute Type
          type: string
          enum: [aks, vmss, container-apps]
          enumNames: [Azure Kubernetes Service, VM Scale Set, Container Apps]
          default: aks
        vmSize:
          title: VM Size
          type: string
          default: Standard_D2s_v3
        minNodes:
          title: Minimum Nodes
          type: number
          default: 2
        maxNodes:
          title: Maximum Nodes
          type: number
          default: 10

    - title: Database Configuration
      required:
        - databaseType
      properties:
        databaseType:
          title: Database Type
          type: string
          enum: [sql-database, postgresql, cosmos-db]
          enumNames: [Azure SQL Database, PostgreSQL Flexible Server, Cosmos DB]
          default: postgresql
        databaseSku:
          title: Database SKU
          type: string
          default: GP_Gen5_2

    - title: Security & CDN
      properties:
        enableWaf:
          title: Enable WAF
          type: boolean
          default: true
        enableFrontDoor:
          title: Enable Front Door
          type: boolean
          default: false

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectName: ${{ parameters.projectName }}
          environment: ${{ parameters.environment }}
          location: ${{ parameters.location }}
          vnetAddressSpace: ${{ parameters.vnetAddressSpace }}
          computeType: ${{ parameters.computeType }}
          vmSize: ${{ parameters.vmSize }}
          minNodes: ${{ parameters.minNodes }}
          maxNodes: ${{ parameters.maxNodes }}
          databaseType: ${{ parameters.databaseType }}
          databaseSku: ${{ parameters.databaseSku }}
          enableWaf: ${{ parameters.enableWaf }}
          enableFrontDoor: ${{ parameters.enableFrontDoor }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: Azure 3-Tier Infrastructure for ${{ parameters.projectName }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
